#set the build language to python
language: python

#Set the python version to 2.7
python: 2.7

# install the codecov pip dependecy 
install:
  - pip install codecov
  
#run the unit test
script: 
  - coverage run cricket.py
  
#put the results back to codecov
after_success:
  - codecov
  
